# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20160325_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='confidence_level',
            field=models.IntegerField(null=True),
        ),
    ]
