# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
        ('posts', '0005_auto_20160412_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domains.Domain'),
        ),
    ]
