# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.Domain'),
        ),
    ]
